name: main workflow
on: push
env:
  docker_username: eatadesse01
  docker_password: ${{ secrets.GITHUB_TOKEN}}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    
    steps:
      - name: clone down repository
        uses: actions/checkout@v4

      - name: set execute permission on the script
        run: chmod +x ci/build-app.sh
        
      - name: run build script  
        run: ./ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh
        
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          
  Linting:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          
  Docker-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: ls
        run: ls -la ci
      - name: build docker
        run: bash ci/build-docker.sh
      - name: push docker
        run: bash ci/push-docker.sh
##      - name: build & push image
##         run: |
##         echo "${{ secrets.DOCKER_PWD}}" |
##         docker imagae build -t docker push eatadesse/project_1
