name: main workflow
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down repository
        uses: actions/checkout@v4

      - name: set execute permission on the script
        run: chmod +x ci/build-app.sh
        
      - name: run build script  
        run: ./ci/build-app.sh
        shell: bash
