name: main workflow
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down repository
        uses: actions/checkout@v4

      - name: set execute permission on the script
        run: chmod +x ci/build-app.sh
        
      - name: run build script  
        run: ./ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh
        
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          
  Linting:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    
    
